public class ArthimaticCalculations {
    public integer Addition(integer x, integer y) {
        integer z = x+y;
        return z;

    }
    public integer Subtraction(integer x, integer y){
        integer z = x-y;
        return z;
    }
    public integer Multiplication( integer x, integer y, integer m){
        integer z = x*y*m ;
        return z;
    }
    public decimal division(integer x, integer y){
        Decimal z = x/ y;
        return z;
    }
}
