public with sharing class ForEachLoopDemo1 {
    public static void iterateIntegerList() {
        list<integer> listInteger = new List<integer>();
        listInteger.add(10); //index=0
        listInteger.add(15); //index=1
        listInteger.add(21); //index=2
        listInteger.add(15); //index=3

        for(integer eachInteger : listInteger){
            system.debug(eachInteger);
        }

    }
}
