public class Ogrenci11 {
    public Ogrenci11() {
        System.debug('yeni bir kayit yapildi');
    }

    public string firstName;
    public string lastName;
    private string schoolName = 'Dream School';
    public string className;
    public string language;
    public Boolean art;
    public Boolean sport;
    public integer ingGrade;
    public integer mathGrade;
    public Integer fenGrade;
}
