public  class SalesforceDeveloper {
    public void myFirstCode() {
        string city = 'Istanbul';
        system.debug('My favorite city is '+ city);
        string movie = 'Babam ve Oglum';
        system.debug('My favorite movis is ' + movie);
        string season = 'Spring';
        system.debug('My favorite season is ' + season);

    }

    public void myFavorites(){
        integer favNum = 777;
        system.debug(favNum);
        string myCity =' Dallas';
        system.debug(myCity);
        system.debug('Favori numaram--> '+ favNum +' ve yasadagim sehir  '+ myCity);

    }
}
